name: stock
description: Dart package for Async Data Loading and Caching.
  Combine local (DB, cache) and network data simply and safely.
version: 1.0.1
homepage: https://github.com/xmartlabs/stock
repository: https://github.com/xmartlabs/stock
issue_tracker: https://github.com/xmartlabs/stock/issues

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  meta: ^1.3.0
  mutex: ^3.0.0
  rxdart: ^0.27.2

dev_dependencies:
  build_runner: 2.2.0
  dart_code_metrics: 4.17.1
  lints: 2.0.0
  mockito: 5.3.0
  test: 1.21.4
  very_good_analysis: 3.0.1
