name: stock
description: Dart package for Async Data Loading and Caching.
  Combine local (DB, cache) and network data simply and safely.
version: 1.1.2
homepage: https://github.com/xmartlabs/stock
repository: https://github.com/xmartlabs/stock
issue_tracker: https://github.com/xmartlabs/stock/issues

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  meta: ^1.3.0
  mutex: ^3.1.0
  rxdart: ^0.28.0

dev_dependencies:
  build_runner: ^2.4.9
  lints: ^3.0.0
  mockito: ^5.4.4
  test: ^1.25.5
  very_good_analysis: ^5.1.0
