name: stock
description: Dart Library for Async Data Loading and Caching
version: 0.0.1
homepage: https://github.com/xmartlabs/dstore

environment:
  sdk: '>=2.17.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  freezed_annotation: 2.1.0
  mutex: 3.0.0
  rxdart: 0.27.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: 2.2.0
  flutter_lints: 2.0.1
  freezed: 2.1.0+1
  mockito: 5.3.0

flutter:
