name: Dart Code Metrics

on: [pull_request]

jobs:
  check:
    name: dart-code-metrics-action
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: dart-code-metrics
        uses: dart-code-checker/dart-code-metrics-action@v2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
